### ISSUE TITLE
train.txt file not found

### ISSUE THREAD

**Issue by aayushag** [visualbuffer/parkingslot#2]
In the yolo_training.py file under the function train() in line 595 "./train.txt" is assigned. Where will we find the train.txt file. Thank you in advance.

**Comment by heyl333** [comment]
so ,how could you find train.txt file

**Comment by amous4822** [comment]
@aayushag any solution to this problem  ?

**Comment by aayushag** [comment]
Yeah I found it here ->[splits.zip](https://cnrpark.it/dataset/splits.zip). But as my PC was getting overheated while training I switched to pre-trained model.
The path provided in the code is incomplete.
Hope it helps!!!

**Comment by amous4822** [comment]
@aayushag where can I find the pre-trained models ?

**Comment by aayushag** [comment]
# YOLO
wget https://pjreddie.com/media/files/yolov3.weights
python ./convert.py ./yolov3.cfg yolov3.weights model_data/yolo.h5


# MASKRCNN
wget "https://github.com/matterport/Mask_RCNN/releases/download/v2.0/mask_rcnn_coco.h5"


As mentioned in the description!

**Comment by aayushag** [comment]
check the description for the same!
